### ISSUE TITLE
nil pointer panic if no config.DataDictionary specified

### ISSUE THREAD

**Issue by babaev** [quickfixgo/quickfix#127]
Currently you can create Initiator instance without providing config.DataDictionary option. However as soon as first non-admin message arrives session.verify panics with "nil pointer dereference" error. 

Should config.DataDictionary option be mandatory? Or should there be an always-ok validator if no  config.DataDictionary option is provided?

**Comment by cbusbey** [comment]
Hm, that should definitely not be mandatory.  Are you running the latest from master?  There were some changes in the validation logic recently, this may have introduced this bug.

**Comment by babaev** [comment]
Yes, running master. I guess the problem is here: 

https://github.com/quickfixgo/quickfix/blob/master/session.go#L95

Creating validator with nil *dataDictionary if no config.DataDictionary

**Comment by bhaan** [comment]
Thank you @babaev for catching this. I believe I've been able to confirm the error you're seeing, and implemented a fix for it here: #128

Feel free to take a look and let me know if you have any concerns.
