### ISSUE TITLE
Set password for initiator

### ISSUE THREAD

**Issue by Kaign** [quickfixgo/quickfix#152]
I just started to investigate this library, and I can't find way to specifiy password(554) for initiator. However there is a Logon type. Is there any significant diffirences for establishing session with password and without?

**Comment by mgatny** [comment]
As with other implementations of quickfix, your opportunity to alter outgoing Admin-level messages is the `ToAdmin()` callback.  Here is an example using the [TradeClient example app](https://github.com/quickfixgo/examples/blob/master/tradeclient/tradeclient.go#L34-37) as a basis:

```go
//ToAdmin implemented as part of Application interface
func (e TradeClient) ToAdmin(msg quickfix.Message, sessionID quickfix.SessionID) {
  if msgType, err := msg.Header.GetString(tag.MsgType); err == nil && msgType == enum.MsgType_LOGON {
    msg.Body.SetField(tag.Username, quickfix.FIXString("Kaign"))
    msg.Body.SetField(tag.Password, quickfix.FIXString("$ecretPa$$word"))
  }
  return
}
```

**Comment by Kaign** [comment]
Thanks, this is what I missed
