### ISSUE TITLE
Bogus Go Report Card Grade

### ISSUE THREAD

**Issue by cbusbey** [quickfixgo/quickfix#154]
With the latest round of generated code changes, quickfixgo appears to break Go Report Card.  The project is getting a poor grade in error.  

Tracks https://github.com/gojp/goreportcard/issues/139

Will likely remove the badge from the README until resolved.

**Comment by hermanschaaf** [comment]
Hi @cbusbey,

I'm one of the Go Report Card maintainers, and I'd like to see what I can do about fixing this. I had a look at the generated files in this repo, and it doesn't seem to me like there would be any easy way for our algorithm to identify them. Would adding a specially-formatted `automatically generated` comment of some sort to the top of these files be a possibility? Is anyone aware of some standard we can follow in this regard in Go?

**Comment by cbusbey** [comment]
@hermanschaaf thanks again for your help!
