### ISSUE TITLE
Session deadlocks if both initiator and acceptor enter the resend state

### ISSUE THREAD

**Issue by mgatny** [quickfixgo/quickfix#169]
If both initiator and acceptor request resend at the same time (e.g. at logon):

- neither resend request will be satisfied
- no heartbeats will be exchanged
- no disconnect will occur
- no message flow, errors, or progress of any kind will occur

Update: this may be fixed by bhaan's latest changes.  Need to re-test.

**Comment by cbusbey** [comment]
Refs #164 #165 #167
