### ISSUE TITLE
cannot access to the mailing list

### ISSUE THREAD

**Issue by reedom** [quickfixgo/quickfix#237]
I got the following error when I visit at https://groups.google.com/forum/#!forum/quickfixgo

    You do not have permission to access this content. (#418)

According to some comments on the web, you might need to ask Google guys to fix the problem.

https://github.com/knockout/knockout/issues/753
http://grokbase.com/t/gg/symfony-devs/1331aqmaxa/unable-to-open-the-users-mailing-list

**Comment by cbusbey** [comment]
@reedom thanks for reporting this.  Try giving it a go now.  A colleague was able to reproduce but it appears to be resolved now.
