### ISSUE TITLE
Place to discuss

### ISSUE THREAD

**Issue by reedom** [quickfixgo/quickfix#248]
I wrote posts to the quickfixgo ML on GoogleGroups. When I looked for them in my mailer, they were no where but found in Spam box. The mailer is Gmail, maintained by Google either. 
Oh no, Google >_<

So I am just wondering GoogleGroups could be place to discuss.
Rather here can be better.

Opinion?

**Comment by cbusbey** [comment]
Well that's no good.  Apologies for the delay, we'll have to put a disclaimer in the documentation to make sure you check your spam folder for mailing list topics.  I've replied to your two issues, can you confirm they were received?

**Comment by reedom** [comment]
I found your posts in the spam box. :p (and I made a mail filter for the ML)
Thank you for your replies.
