### ISSUE TITLE
ResetOnLogon=Y does not send ResetSeqNumFlag (tag 141)=Y

### ISSUE THREAD

**Issue by ocZio** [quickfixgo/quickfix#278]
Using the following configuration

`ResetOnLogon=Y and ResetOnLogout=Y`

I can see that the tag 141 is not send during the logon process?

`ToAdmin: 8=FIX.4.4 9=75 35=A 34=1 49=XXX 52=20170216-15:20:27.245 56=XXX 98=0 108=30 10=230`

Am I missing something ? :-)

Thanks,

**Comment by cbusbey** [comment]
Hi @ocZio Is your app an Acceptor or Initiator? ResetOnLogon is a Acceptor only configuration.

**Comment by ocZio** [comment]
Sorry, forgot to close this issue, indeed the documentation did mention briefly that the ResetOnLogon is only for Acceptor. 

It was a little bit confusing since the Client (Initiator) can actually request the sequence reset during the Logon.
