### ISSUE TITLE
TLS Configuration

### ISSUE THREAD

**Issue by ocZio** [quickfixgo/quickfix#279]
Currently the defaultTLSConfig() enforces the minimum version for TLS to be 1.2 (tls.VersionTLS20). Most of the banking/financial institutions are lagging when it comes to using the latest technologies. 

Can we have some sort of configuration file option to specify the minimum required TLS version ?

Thanks,

**Comment by cbusbey** [comment]
Hi @ocZio, this would be a nice config option, looking forward to this change.  Thanks!

**Comment by ocZio** [comment]
Hi @cbusbey I have made an initial PR but for some reason the tests are failing with TRAVIS, would you mind having a look at #280 ?

Thanks.
