### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by dominhtri1995** [quickfixgo/quickfix#287]
Hi,

Is quickfixGo multithreaded when sending message and receiving message in the FromApp function ? I see no mention of it in the documentation and when i try to send and receive message concurrently I get back a bad result. I'm not sure if its a bug in my logic handling or because i'm doing something wrong with quickfixGo in multithreaded application

Thanks

**Comment by cbusbey** [comment]
Could you be more specific as to the behavior you are seeing?  Are you saying that you cannot send a message from the FromApp callback?  That should be supported behavior as it is what the echo server does as part of our acceptance testing framework

https://github.com/quickfixgo/quickfix/blob/master/_test/echo_server.go

**Comment by johndydo** [comment]
May be related to my fix in https://github.com/quickfixgo/quickfix/pull/329

**Comment by cbusbey** [comment]
Yeah I think we can close this issue for now.  Please re-open if the issue remains with the latest, but I agree that @johndydo 's fix may help.
