### ISSUE TITLE
Group Field Generation

### ISSUE THREAD

**Issue by cbusbey** [quickfixgo/quickfix#30]
Generate fields for parsinging, writing repeating groups

**Comment by rfru** [comment]
@pfeairheller were you able to get something working here? I'm also in need of this functionality.

**Comment by nick-ctr** [comment]
@cbusbey @pfeairheller Any progress here? Would be happy to help test any implementation.

**Comment by jfyuen** [comment]
There is an unclear usage of a repeating group with GroupTemplate, whether a group field should have all fields in the templates (encountering an unknown field stops the group), or may the template contain only part of the full group.
There is 2 exclusive pull requests to check them (please only take one of them or none): 
 - #49 : to allow partial templates
 - #48 : adding more checks, but stop on an unknown field

The API for reapeating groups is still not very user friendly but much better than a dirty hack I made a few months ago!

**Comment by cbusbey** [comment]
Just an update here, a rough cut of repeating group is in master now (and works!) but this is still in active development.  Trying to clean up some cruft and adding documentation as we go.

**Comment by cbusbey** [comment]
Closing issue, verified functionality with [example apps](http://github.com/quickfixgo/examples) :dancer::dancer::dancer:
