### ISSUE TITLE
Sorting Tags in a Group Field

### ISSUE THREAD

**Issue by cats101** [quickfixgo/quickfix#300]
Hi, I'm trying to change the order of the tags of a `marketdataincrementalrefresh.NoMDEntries` field, I've tried the `Swap` method and it seems to change the order of the underlying `Tags` array, but the serialized message is always the same. Is there a way to do that?

**Comment by cbusbey** [comment]
Hello,

The tag ordering within a group is determined by the order as they appear in the data dictionary that generated the group.  If you need to change the field ordering, you should customize the data dictionary for your session and regenerate the messages with your customizations.  See the [README](https://github.com/quickfixgo/quickfix#fix-message-generation) for details
