### ISSUE TITLE
TLSConfig is unusable for non client side verification

### ISSUE THREAD

**Issue by chackett** [quickfixgo/quickfix#311]
Hello,

I want to use QuickFixGo to connect to an acceptor via TLS but not provide socket private key file (for client to server auth).

This doesn't provide the result I would like, if a private key is not supplied the `loadTLSConfig()` returns a default config, with `insecureSkipVerify` set to true. It also doesn't set the minimum TLS version to what was specified in the config. And I also don't know why the default minimum TLS version is not the lowest version.

I am going to add a fix for this that will still build the TLS config and honour the provided config, event if client side connect is not required. With this in mind, how do you suggest I allow the user to specify that TLS is required? I propose adding `TLSConnect=Y/N` to the config file.

Thanks

**Comment by cbusbey** [comment]
Hi @chackett.  Could you clarify your use case?

Is it the case that you don't want the client to verify the server? Or you don't want the server verifying the client?

**Comment by chackett** [comment]
Hi

I am currently acting as a client. I do wish that the client validate the server but I don't see why I would need to specify a private key for that.

In the event that a private key is not specified, loadTLSConfig(), kind of just makes some assumptions about a default config and returns that. It doesn't proceed to parse the rest of the config.

What do you think? I can submit a PR.

**Comment by cbusbey** [comment]
It seems like your use case is unique.  Usually client key creation is not an issue, and in my experience, acceptors will require the client pub key to authorize connectivity. 

In any case, I think this is worth a bigger design change.  [tls.Config](https://golang.org/pkg/crypto/tls/#Config) offers a lot of options.  I don't think it is worth polluting the config options as new tls customizations come up.  Ideally the available config options handle the vanilla, most likely setup.  I wonder if there is a better way to abstract the connection interface so that API clients with use cases such as yours could inject your own tls.Config?

**Comment by chackett** [comment]
I don't think the case is unique.

With TLS there is always key exchange with the server so it can be validated. Optionally, the client can also specify a key if the server requires authentication (mutual). It is an optional case that I do not require. We don't know when others may/may not want it.

I think the case of "no client authorisation" should be supported. I don't think that adding `SocketUseSSL` is pollution as it exists in other QuickFix implementations. What I have mentioned isn't really a TLS customisation but rather one of the two modes of connection / authentication.

The problem I have with the current implementation is that I am forced to provide client certs in order to connect. [tls.Config](https://golang.org/pkg/crypto/tls/#Config) doesn't force the other settings.

How about we get `loadTLSConfig()` load the config as you previously did but also load it correctly when client auth is not required (As I have done locally). So it covers both scenarios.

Also, I think that `loadTLSConfig()` should be done in the constructor perhaps. That way we could then offer up an exported member variable TLSConfig() that would allow developers decorate it as they see fit.

**Comment by chackett** [comment]
Hey @cbusbey - I will put together a PR and take it from there. I will try and keep it abstract etc but at least cover the other case of TLS config with no client side auth.

**Comment by chackett** [comment]
I am aborting this request as I have found a workaround.

Basically, I have created some self-signed certs and provide them via the config. I have been lucky that the FIX Acceptor I am connecting to doesn't complain about these.

Now that the client certs are provided to QuickFix, it generates a usable `TLSConfig` object.

For reference, I used the following gist to create the certs. For some reason it insisted on providing a password to the `.pem` file so I used the second link to remove the password.
1. https://gist.github.com/mtigas/952344
2. https://knowledge.rapidssl.com/support/ssl-certificate-support/index?page=content&actp=CROSSLINK&id=SO5292

**Comment by cgst** [comment]
I also think client auth should be optional (i.e. the server I'm using does not need to authenticate the client). I can work around it by creating a dummy self-signed key pair but this seems like a bug to me. loadTLSConfig shouldn't assume I want mutual TLS.
