### ISSUE TITLE
What is the purpose of FileLogPath, can we disable?

### ISSUE THREAD

**Issue by chackett** [quickfixgo/quickfix#313]
Hello,

I am just wondering about the configurable item `FileLogPath` which stores all the messages sent/recvd between client/server.

After running my service for a couple of weeks I have a 2.5GB file.

How can I disable this feature? I don't need access to these in production.

Many thanks

**Comment by cbusbey** [comment]
If using the file logger, this is the directory that logs are written to.  You can either not use the file logger or perhaps a better production setup, a log rotator
