### ISSUE TITLE
Building quickfix on a windows machine

### ISSUE THREAD

**Issue by Moataz-E** [quickfixgo/quickfix#319]
Hi,

I am currently trying to build quickfix on a windows machine with GnuWin32 installed (so make and grep commands are available). When I run `make` in the quickfixgo directory, I get the following error:

```
go vet `go list ./... | grep -v quickfix/gen`
can't load package: package `go: cannot find package "`go" in any of:
        C:\Go\src\`go (from $GOROOT)
        C:\Users\elmasm\go\src\`go (from $GOPATH)
can't load package: package list: cannot find package "list" in any of:
        C:\Go\src\list (from $GOROOT)
        C:\Users\elmasm\go\src\list (from $GOPATH)
make: *** [vet] Error 1
```

Can you guys shed some light on why I am getting the above error?

**Comment by cbusbey** [comment]
This doesn't appear to be an issue with quickfixgo, but with your go install.  Take a look at 

https://golang.org/doc/install
https://github.com/golang/go/wiki/SettingGOPATH
