### ISSUE TITLE
Add my own additional tags

### ISSUE THREAD

**Issue by Moataz-E** [quickfixgo/quickfix#321]
Hi,

I am trying to integrate with a custom FIX application that uses additional messages and components. So far, I've finished the custom xml file in my own project's directory.

My question is, how can I also extend the `tag.go` file with the the tags for the additional FIX messages without having to use a modified `quickfix` package?

**Comment by cbusbey** [comment]
Add custom tags to your data dictionary and generate fix messages, tags, and fields using the fix generator.  See https://github.com/quickfixgo/quickfix#fix-message-generation for details.

**Comment by Moataz-E** [comment]
Sorry, where should I be adding the tags in the data dictionary? I added the tags to the `tag.go` file.

**Comment by cbusbey** [comment]
You can add custom field definitions to the `<fields>..</fields>` xml element of your data dictionary.  You will need to add these tags here before adding the custom fields to your message definitions.
