### ISSUE TITLE
Empty generated enum 

### ISSUE THREAD

**Issue by Moataz-E** [quickfixgo/quickfix#322]
Hi,

I am running `generate-fix.go` on the attached fix schema but the program finishes with errors specifically related to an empty `enums.generated.go` file.

The enum file's content is just the following:

```
package
```

Do you know what the issue could be?

**Comment by Moataz-E** [comment]
Hi, it turns out the issue is I can't have spaces or full stops in the description attribute of the value field.

**Comment by cbusbey** [comment]
related #305

**Comment by Moataz-E** [comment]
indeed, I am using a custom Bloomberg FIX protocol.
