### ISSUE TITLE
Add deep copy for Messages

### ISSUE THREAD

**Issue by zeeke** [quickfixgo/quickfix#338]
Hi,

As far as I know, `quickfix.Message` objects referred on received messages are created by `quickfix.messagePool` and pooled for later use. This optimization prevents me to save a Message reference, i.e. in an array.

It would be useful to have a Message deep copy function in order to get an isolated copy of the message. At the moment, the only way I found to achieve this result involve dumping and parsing back the message:

```go
messageCopy := quickfix.NewMessage()
quickfix.ParseMessage(messageCopy, bytes.NewBufferString(originalMessage.String()))
```
What do you think about it?

**Comment by blutack** [comment]
Just as a note, it seems like the current deep copy may not be totally deep.

I have code doing this:
```go
func (f *FixHandler) onSecurityDefinition(message securitydefinition.SecurityDefinition, sessionID quickfix.SessionID) quickfix.MessageRejectError {
	m := quickfix.NewMessage()

	err :=message.ToMessage().CopyInto(m)

	if err != nil {
		logger.WithError(err).Warn("Couldn't copy message")
	}

	f.SecurityDefinitions <- securitydefinition.FromMessage(m)

	return nil
}
```
I have a test harness which replays a known good security definition message x number of times.

When ramping up the number of messages received I start to get strange parse errors, and looking at the parsed message structure it appears that something in the received data or message is getting corrupted.

Replacing the ```err :=message.ToMessage().CopyInto(m)``` with ```quickfix.ParseMessage(messageCopy, bytes.NewBufferString(originalMessage.String()))``` resolves the issue.

I'm not sure how quickfix operates internally but the line ```to.rawMessage = m.rawMessage``` does look potentially of interest.

Thanks for the library!

**Comment by ethanf** [comment]
I just ran into the same issue as @blutack where `CopyInto()` does not do a full deep copy.
