### ISSUE TITLE
How do I create an acceptor that can create dynamic sessions?

### ISSUE THREAD

**Issue by Toormi** [quickfixgo/quickfix#339]
Hi, all

I want to create a service that handles the FIX protocol and can accept dynamic connections from thousands of users,Just like this https://docs.pro.coinbase.com/#fix-api. I can't create sessions for each user in the configuration file.  what should I do.

**Comment by Toormi** [comment]
I am sorry for asking for help in issues.

**Comment by reddec** [comment]
Implemented in #377
