### ISSUE TITLE
Create a go.mod

### ISSUE THREAD

**Issue by andradei** [quickfixgo/quickfix#340]
So it is better supported by Go Modules.

**Comment by jameskilroe** [comment]
Hi, is this in the roadmap?

Running into the same TimestampPrecision error, when using a docker container and GoModules

**Comment by cbusbey** [comment]
We would gladly accept a contribution that introduces support for go modules

**Comment by jimidle** [comment]
You can do a 

go get -u on @master 

to get around this. Or, at least, that worked for me
