### ISSUE TITLE
Non-compliant sequence behavior on Initiator Logon with ResetSeqNumFlag 141=Y

### ISSUE THREAD

**Issue by edmundofuentes** [quickfixgo/quickfix#345]
Hey there,

I've found a non-compliant behavior on the Initiator when doing a LOGON with the ResetSeqNumFlag tag set to 141=Y.

### Behavior & Context
To add the flag, I'm overriding the message in the `ToAdmin()` function of my application interface and I'm adding the ResetSeqNumFlag only if the first message is a LOGON (MsgType=A).

When the server (Acceptor) receives my LOGON two scenarios could happen:
- A) Accepts my connection normally, the Acceptor sends the LOGON response as Seq 1 and from there the Initiator continues with Seq 2 (Seq 1 was the LOGON message)
- B) Accepts my connection, but _also replies with a ResetSeqNumFlag_, in which case quickfix restarts my session and the Initiator continues with Seq 1 again.

However, I've just found out that behavior B is non-compliant according to the FIX 4.2 Spec:

> When using the ResetSeqNumFlag to maintain 24 hour connectivity and establish a new set of sequence numbers, the process should be as follows. Both sides should agree on a reset time and the party that will be the initiator of the process. Note that the initiator of the ResetSeqNum process may be different than the initiator of the Logon process. One side will initiate the process by sending a TestRequest and wait for a Heartbeat in response to ensure of no sequence number gaps. Once the Heartbeat has been received, the initiator should send a Logon with ResetSeqNumFlag set to Y and with MsgSeqNum of 1. The acceptor should respond with a Logon with ResetSeqNumFlag set to Y and with MsgSeqNum of 1. At this point new messages from either side should continue with MsgSeqNum of 2. It should be noted that once the initiator sends the Logon with the ResetSeqNumFlag set, the acceptor must obey this request and the message with the last sequence number transmitted “yesterday” may no longer be available.

I've read the spec and it seems that only on this particular case the sequence must be reset and begin at 2 instead of 1, which I find very weird, but since that's how it's written on the spec that's how the vendors have implemented it.

### Problem
I've looked at the library and found that the ResetSeqNumFlag is correctly being parsed and interpreted in the `handleLogon` function and it calls the `MessageStore.Reset()` function that resets the sequence.

```go
// github.com/quickfixgo/quickfix/session.go
func (s *session) handleLogon(msg *Message) error {
....
        resetStore := false
	if s.InitiateLogon {
		s.log.OnEvent("Received logon response")
	} else {
		s.log.OnEvent("Received logon request")
		resetStore = s.ResetOnLogon

		if s.RefreshOnLogon {
			if err := s.store.Refresh(); err != nil {
				return err
			}
		}
	}

	var resetSeqNumFlag FIXBoolean
	if err := msg.Body.GetField(tagResetSeqNumFlag, &resetSeqNumFlag); err == nil {
		if resetSeqNumFlag {
			s.log.OnEvent("Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1")
                        // WRONG: THIS SPECIFIC CASE SHOULD RESET TO 2 ACCORDING TO THE SPEC
			if !s.sentReset {
				resetStore = true
			}
		}
	}

	if resetStore {
		if err := s.store.Reset(); err != nil {
			return err
		}
	}
....
}
```

```go
// github.com/quickfixgo/quickfix/store.go MessageStore

func (store *memoryStore) Reset() error {
	store.senderMsgSeqNum = 0
	store.targetMsgSeqNum = 0
	store.creationTime = time.Now()
	store.messageMap = nil
	return nil
}
```

The `Reset()` function is called in many other places in the codebase, where I believe it actually needs to be reset to zero. However, in the particular case of an Initiator that receives a LOGON reply with the ResetSeqNumFlag tag set, it should *not* reset to 0, instead it should reset to 1 (so the next message sent would be Seq 2).

### Proposed Solution
Modify the `handleLogon()` function in the `session`, something like:

```go
// github.com/quickfixgo/quickfix/session.go
func (s *session) handleLogon(msg *Message) error {
	//Grab default app ver id from fixt.1.1 logon
	if s.sessionID.BeginString == BeginStringFIXT11 {
		var targetApplVerID FIXString

		if err := msg.Body.GetField(tagDefaultApplVerID, &targetApplVerID); err != nil {
			return err
		}

		s.targetDefaultApplVerID = string(targetApplVerID)
	}

	resetStore := false
	if s.InitiateLogon {
		s.log.OnEvent("Received logon response")
	} else {
		s.log.OnEvent("Received logon request")
		resetStore = s.ResetOnLogon
		if resetStore {
			if err := s.store.Reset(); err != nil {
				return err
			}
		}

		if s.RefreshOnLogon {
			if err := s.store.Refresh(); err != nil {
				return err
			}
		}
	}

	var resetSeqNumFlag FIXBoolean
	if err := msg.Body.GetField(tagResetSeqNumFlag, &resetSeqNumFlag); err == nil {
		if resetSeqNumFlag {
			s.log.OnEvent("Logon contains ResetSeqNumFlag=Y, resetting sequence numbers, setting sender sequence to 2")
			if !s.sentReset {
				resetStore = true
				if err := s.store.Reset(); err != nil {
					return err
				}
				if err := s.store.SetNextSenderMsgSeqNum(2); err != nil {
					return err
				}
			}
		}
	}

	if err := s.verifyIgnoreSeqNumTooHigh(msg); err != nil {
		return err
	}

	if !s.InitiateLogon {
		var heartBtInt FIXInt
		if err := msg.Body.GetField(tagHeartBtInt, &heartBtInt); err == nil {
			s.HeartBtInt = time.Duration(heartBtInt) * time.Second
		}

		s.log.OnEvent("Responding to logon request")
		if err := s.sendLogonInReplyTo(resetStore, resetSeqNumFlag.Bool(), msg); err != nil {
			return err
		}
	}
	s.sentReset = false

	s.peerTimer.Reset(time.Duration(float64(1.2) * float64(s.HeartBtInt)))
	s.application.OnLogon(s.sessionID)

	if err := s.checkTargetTooHigh(msg); err != nil {
		return err
	}

	return s.store.IncrNextTargetMsgSeqNum()
}
```

I'm not that familiar with the codebase, so I don't know if there might be unintended side effects of modifying this, but this doesn't seem to be a breaking change at all.

I will shortly send a Pull Request with this change for you to review.
Cheers!

**Comment by edmundofuentes** [comment]
Sample logs: https://github.com/quickfixgo/quickfix/pull/346#issuecomment-445854062

**Comment by edmundofuentes** [comment]
As an update, we've been using our proposed patch on production for more than a month against two independent instances of SunGard. So far so good.

**Comment by cbusbey** [comment]
>B) Accepts my connection, but also replies with a ResetSeqNumFlag, in which case quickfix restarts my session and the Initiator continues with Seq 1 again.

Do you have logs that demonstrate this behavior? I don't follow your `WRONG` note here,

```go
var resetSeqNumFlag FIXBoolean
	if err := msg.Body.GetField(tagResetSeqNumFlag, &resetSeqNumFlag); err == nil {
		if resetSeqNumFlag {
			s.log.OnEvent("Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1")
                        // WRONG: THIS SPECIFIC CASE SHOULD RESET TO 2 ACCORDING TO THE SPEC
			if !s.sentReset {
				resetStore = true
			}
		}
	}
```

Doesn't the `if !s.sentReset` prevent the reset you are describing?

**Comment by edmundofuentes** [comment]
This is an older log I found before we fixed the issue in our client. If more logs are needed I could roll back the changes and test against the UAT Environment of one of our brokers.

On the 3rd message in the log (at 16:16:03.703910), the Initiator (us) has reset its sequence and it's sending SeqNum 1, but the Acceptor is expecting SeqNum 2.

```
2018/12/03 16:15:33.703587 8=FIX.4.2|9=74|35=A|34=1|49=INITIATOR|52=20181203-16:15:33.703|56=ACCEPTOR|141=Y|98=0|108=30|10=019|

2018/12/03 16:15:33.777326 8=FIX.4.2|9=70|35=A|34=1|49=ACCEPTOR|52=20181203-16:15:33|56=INITIATOR|98=0|108=30|141=Y|10=071|

// LOGON was "successful", waiting for first heartbeat..

2018/12/03 16:16:03.703910 8=FIX.4.2|9=62|35=0|34=1|49=INITIATOR|52=20181203-16:16:03.703|56=ACCEPTOR|10=210|

2018/12/03 16:16:03.757137 8=FIX.4.2|9=101|35=5|34=2|49=ACCEPTOR|52=20181203-16:16:03|56=INITIATOR|58=MsgSeqNum too low, expecting 2 but received 1|10=182|

2018/12/03 16:16:03.757253 8=FIX.4.2|9=56|35=5|34=2|49=INITIATOR|52=20181203-16:16:03.757|56=ACCEPTOR|10=201|
```

I believe the issue is that the expected behavior is different depending on who initiated the ResetSeqNumFlag, and that specific part in the `handleLogon()` method does not differentiate if the current session is an Initiator or an Acceptor.

Please review my proposed PR, since I made some slight revisions between the time I wrote this Issue and when I pushed the last commit to my PR. 

Cheers!

**Comment by cbusbey** [comment]
I attempted to recreate this using a simple initiator and acceptor in the scenario you described but I was unable to reproduce.  Assuming the ResetSeqNumFlag is set in ToAdmin on Logon Messages in the message _body_ the library should work as expected.  Is it possible you were setting this flag in the message Header?  I was only able to reproduce your behavior as described by setting the field there, which is not expected.

Furthermore, there have been some changes added recently to have the engine send ResetSeqNum automatically by configuration (ResetOnLogon). We encourage you to use this configuration instead of setting the ResetSeqNum flag manually.
