### ISSUE TITLE
Initiator not sending ResetSeqNumFlag on logon with ResetOnLogon=Y

### ISSUE THREAD

**Issue by cbusbey** [quickfixgo/quickfix#351]
Edited title, should be for initiators

**Comment by ijufumi** [comment]
Initiator too.

I think that QuickFIX/J is a good reference.
https://github.com/quickfix-j/quickfixj/blob/master/quickfixj-core/src/main/java/quickfix/Session.java#L2005
https://github.com/quickfix-j/quickfixj/blob/master/quickfixj-core/src/main/java/quickfix/Session.java#L840
