### ISSUE TITLE
Behavior when PersistMessages = N is incorrect

### ISSUE THREAD

**Issue by ijufumi** [quickfixgo/quickfix#361]
In [configuration page](https://www.quickfixgo.org/docs/configuration.html),

> If set to N, no messages will be persisted. This will force QuickFIX/Go to always send GapFills instead of resending messages. Use this if you know you never want to resend a message. Useful for market data streams.

But, when gaps occur, always send "Resend Request", regardless of the setting of PersistMessages.

**Comment by ijufumi** [comment]
Expected behavior is like QuickFIX/J.

https://github.com/quickfix-j/quickfixj/blob/master/quickfixj-core/src/main/java/quickfix/Session.java#L1288
https://github.com/quickfix-j/quickfixj/blob/master/quickfixj-core/src/main/java/quickfix/Session.java#L2219

**Comment by cbusbey** [comment]
Sorry, I don't follow, what is the behavior that you are seeing that is incorrect?  Is the library not sending gap fills as expected?

**Comment by ijufumi** [comment]
Apologize for my late response.

Sorry, I had misunderstood this behavior.
This library is no problem.
