### ISSUE TITLE
ready for production use?

### ISSUE THREAD

**Issue by erikash** [quickfixgo/quickfix#37]
Hi,
I'm the CTO of a Fintek startup, we require a fix protocol solution and nearing production in a couple of months.

First, congrats! 
The project is very impressive! and I think that it's a very important contribution to the open-source community and to the FIX community in particular.

In the next couple of weeks we'll start integration with a sell side broker.

@cbusbey : After seeing this repository we started wondering :
1. Is it ready for production use in your opinion?
2. Are you planning on maintaining it for the next couple of months/year?

Thanks in advance,
Erik.

**Comment by cbusbey** [comment]
Hi Erik,

Just a quick update here.  I am happy to report that I am back at Connamara and will be looking forward to continue to maintain QuickFIX/Go.

**Comment by erikash** [comment]
Thanks!
That's great new for us :)
Currently we're working with a proprietary API implemented in C++ with node.js bindings.

I'll be looking forward to working with this library, good luck! :+1:
