### ISSUE TITLE
Socks Proxy

### ISSUE THREAD

**Issue by andre-l-mm** [quickfixgo/quickfix#375]
Based on documentation, it looks like QuickFixJ provides configuration settings that allow you to connect to a FIX server through a SOCKS proxy. 

I could not find the same options available on [quickfixgo documentation] (https://www.quickfixgo.org/docs/configuration.html). 

Is it possible to connect to a FIX Server through a SOCKS proxy with quickfixgo?

**Comment by cbusbey** [comment]
The library itself does not offer this out of the box.

**Comment by andre-l-mm** [comment]
Thank you for the confirmation. I know this question now goes beyond the library, but Would you know of any alternative way to configure the network locally to route traffic through the proxy?
