### ISSUE TITLE
Application does not get signalled when the other side disconnects

### ISSUE THREAD

**Issue by rpkamp** [quickfixgo/quickfix#38]
The comment on the OnLogout in `application.go` says `Notification of a session logging off or disconnecting.`, but while I can see in the code that this method will be called on a log out, I don't see it called anywhere when we are disconnected because the other party stopped responding.
I think it's just a matter of adding `s.application.OnLogout(s.sessionID)` to `func (s *Session) onDisconnect()` in `session.go`.

I would really like to get this notification so we can try to reconnect or otherwise take that specific fix connection out of the pool (at least temporarily)

If you want I can send a pull request.

**Comment by cbusbey** [comment]
Hi @rpkamp, yes a pull request would definitely be appreciated.  Thanks!

**Comment by rpkamp** [comment]
See https://github.com/quickfixgo/quickfix/pull/39
