### ISSUE TITLE
FIX Message Conversion to Struct

### ISSUE THREAD

**Issue by Rahul7794** [quickfixgo/quickfix#382]
I have a FIX message that I have received from one of the FIX API:

```8=FIX.4.4\u00019=145\u000135=D\u000134=4\u000149=ABC_DEFG01\u000152=20090323-15:40:29\u000156=CCG\u0001115=XYZ\u000111=NF 0542/03232009\u000154=1\u000138=100\u000155=CVS\u000140=1\u000159=0\u000147=A\u000160=20090323-15:40:29\u000121=1\u0001207=N\u000110=194\u0001```
I am using quickfixgo to connect to the API but I am not able to find a way to parse the message to a human-readable struct. I am very new to FIX protocol and finding it hard to find a way to achieve the same. Any help would be much appreciated.

**Comment by ZhangYet** [comment]
I think you could write a parser like [this](https://gist.github.com/ZhangYet/66d570db101fdd01ad8f25d724215925).

Hope it could help.

**Comment by Rahul7794** [comment]
I was able to build my own converter. Thanks ! Hence closing this
