### ISSUE TITLE
Resends not working with messages that have groups

### ISSUE THREAD

**Issue by imirkin** [quickfixgo/quickfix#386]
It reads in the message from the message store, adds the PossDupFlag/SendingTime, and then reserializes the message. As part of that serialization, it sorts all the fields which messes up groups. We have a data dictionary set on the session.

One idea is to initialize the resend message with a no-op ordering for the body, esp since that doesn't change.

**Comment by cbusbey** [comment]
I think this might be highly related to #276

**Comment by imirkin** [comment]
Yes. Highly related. I was sure this worked, but clearly not. Closing this as a dup. I did look at the existing issues, but must have glossed over this one.

Right now I'm thinking of just reusing the bodyBytes -- that seems like it could work.
