### ISSUE TITLE
Publicly expose underlying net.Conn connections 

### ISSUE THREAD

**Issue by mirceapasoi** [quickfixgo/quickfix#388]
I'm using the `Acceptor` from `quickfixgo` to maintain a bunch of FIX connections, and I'd like to implement IP whitelisting functionality.

From what I can tell, the `Acceptor` maintains a private `net.Listener` for managing the TCP connections:
https://github.com/quickfixgo/quickfix/blob/master/acceptor.go#L140

Would it be possible to publicly expose the underlying `net.Conn` connections, so I can access `RemoteAddr` for whitelisting?

**Comment by cbusbey** [comment]
Interesting, but I'm curious why iptables or some other firewall solution is not sufficient?

**Comment by mirceapasoi** [comment]
The IP whitelist is different per user and it's stored in the database, so I don't think iptables or a firewall solution would work.

Does exposing this require significant changes to the library?

**Comment by mirceapasoi** [comment]
@cbusbey Is this something that could be added to the library?

**Comment by cbusbey** [comment]
this sounds pretty unique, i'm not sure this is something other quickfix implementations expose.  we'd certainly entertain a pull request

**Comment by StanChe** [comment]
Hi guys, I've also stumbled upon the same request while trying to auth the sessions. My preferred option is to use mTLS with certificate being tied to both the IP-range and SenderCompID. But without the net.Conn I don't see a way to get the client's certificate, but only to rely on the tls package to let only allowed clients. But this way I'll still be exposed to SenderCompID spoofing. Did anyone have such problems?
I'm thinking about introducing an optional instance of  
``` 
interface ConnectionValidator{
    Validate(netConn net.Conn, session SessionID) error
}
```
to the `Acceptor` (with an appropriate Setter) and if it's set - call it on the connection and the session. This way library clients will be able to set any verifying logic they might need. Any suggestions?
