### ISSUE TITLE
generate-fix no longer usable - pulls in wrong enums/tags/etc

### ISSUE THREAD

**Issue by imirkin** [quickfixgo/quickfix#396]
Pretty much every FIX integration requires some amount of custom (since it's a standard like XML is a standard). Frequently new tags are added, enum values, etc (not to mention messages being entirely rejiggered). Previously it was possible to have a bunch of data dictionaries, each in its own bizarro-land, with their own enums/etc. However since commit c9d06ba5abc677b34cd991767290af4501446390, this is no longer possible. The quickfixgo tags/enums are always used, which leads to non-compiling generated files.

Why was this change made? Can it be reverted?

**Comment by cbusbey** [comment]
This appers to be resolved in latter commits by way of the pkg-root flag.    

https://github.com/quickfixgo/quickfix/commit/1b43940d5626673867e1f8d61312a2ef6fdb074e

Closing for now, let us know if this does not resolve the original issue.
