### ISSUE TITLE
There is no generate-fix in bin directory after installation

### ISSUE THREAD

**Issue by duy-chk** [quickfixgo/quickfix#445]
I have just installed the package but there is no generate-fix binary built in bin directory. Could anyone help to check pls? Thank you!

**Comment by ackleymi** [comment]
Hi, we're going through a few changes and growing pains around the generator tool, it will be fixed and greatly improved soon! For now you can use `go install github.com/quickfixgo/quickfix/cmd/generate-fix@latest` and that will install the binary either in ~/go/bin or the dir you have set for $GOBIN

**Comment by duy-chk** [comment]
Hi @ackleymi, thank you for your helps! I have installed it successfully by using your command.
