### ISSUE TITLE
Improving health-checking capability

### ISSUE THREAD

**Issue by imirkin** [quickfixgo/quickfix#451]
If one puts haproxy in front of a FIX server, the haproxy wants to be able to health check the connection. It seems impossible to do this quietly. For example if I have it send a valid FIX message to a bogus comp id, the acceptor will complain about a missing session. If I catch it in the connection validator, then I get an error about connection validation failing. If I do none of this, then I end up with "connection reset by peer" errors.

Ideas welcome.

**Comment by steelkorbin** [comment]
Just goroutine your FIX endpoint and a second http endpoint on a different port, have the HA hit your second service for health checks. Or if you have a more advanced environment you could use an agent-check service with HA. Now your session issues might need the sticky bit/session in your HA. Just some hip shot guess work for ya.

**Comment by imirkin** [comment]
I looked at the agent option prior to filing this issue. My concern is that it's not a true representation of the healthiness of the service. It's just what the program thinks internally is going on. Better than nothing, but also not the real thing.

**Comment by steelkorbin** [comment]
Well, if you want to know about the errors, conditions, and health inside
of your FIX service, that does not go to your HA, you will code that into
your FIX service to send to a logging / monitoring / SIEM / SMS / EMAIL /
Dashboard / etc... service for you to see what is going on and make
decisions. Then you will get a better idea about what is taking your FIX
service down and fix it. HA is a UP / DOWN / REJECT / ALLOW / MOVE-ON
affair at the physical network level only, use it for that.

**Comment by imirkin** [comment]
Right. But my point is that just because I *think* that the service is accepting connections doesn't mean that it is. Perhaps something got out of sync. The only real way to know is to open a connection on the port...

**Comment by imirkin** [comment]
Ended up implementing the agent-check option. Note that this doesn't work without the regular "check" also enabled, which had to be pointed at the agent-check port as well, otherwise we kept getting the connection reset errors (naturally).
