### ISSUE TITLE
Is quickfixgo thread-safe? get data race warning and  concurrent map read and map write panic

### ISSUE THREAD

**Issue by litaotao** [quickfixgo/quickfix#456]
Hi, we have a system, simply speaking, it's designed as a master go process accepting orders and assign one routine dealing one order.

the problem is where are are lots of orders, like 2k~5k per second, there are many data race warnings and sometimes even go panic with message: concurrent map read and map write panic

can anyone confirm that this package is thread-safe?

**Comment by waheedoo** [comment]
Hi @litaotao, I'm facing the same issue. You closed this ticket without an update, I'm curious to know if you manage to solve the race conditions in your case?

Thanks!
