### ISSUE TITLE
Incorrect NumInGroup count for repeating group

### ISSUE THREAD

**Issue by duy-chk** [quickfixgo/quickfix#460]
I am keeping receiving this error for validating the below message. The number is correct (268=8) which I can manually count.  Could anyone show me the way to resolve this please? Thank you!

8=FIX.4.2 9=0485 35=W 34=1652 49=XYZ 52=20210901-09:48:20.444 56=xyz 262=ABCUSD 5000=0 109=abc 55=BTCUSD 268=8 269=0 270=47553.20 278=36 271=5.00000000 290=1 269=0 270=47550.20 278=32 271=7.00000000 290=2 269=0 270=47547.20 278=2 271=10.00000000 290=3 269=0 270=47544.20 278=102 271=50.00000000 290=4 269=1 270=47597.24 278=72 271=5.00000000 290=1 269=1 270=47600.24 278=81 271=7.00000000 290=2 269=1 270=47603.24 278=26 271=10.00000000 290=3 269=1 270=47606.24 278=50 271=50.00000000 290=4 10=102

But current validation works fine with this

2021/09/01 07:54:50.402570 8=FIX.4.4 9=187 35=W 49=xyz 56=abc 34=513 52=20210901-07:54:50.248 262=ABCUSD 48=5004 22=8 268=2 269=0 270=47152.03 271=100 272=20210901 273=07:54:50.245 269=1 270=47185.46 271=100 10=145

**Comment by ackleymi** [comment]
@duy-chk I believe this is resolved in https://github.com/quickfixgo/quickfix/releases/tag/v0.9.2 please re-open issue if that is not the case.
