### ISSUE TITLE
Editing Sequence number files on host fails to change sequence numbers

### ISSUE THREAD

**Issue by adam-talos** [quickfixgo/quickfix#464]
If I edit the sequence numbers under .senderseqnums or .targetseqnums in vi or similar, it will fail due to an invisible carriage return added to the file by vi.  The filestore implementation just takes the contents of the file and interprets it as a number which fails due to the trailing character.

If we do a trim before interpreting the string, the process will succeed.

**Comment by ackleymi** [comment]
#463 was merged and released with version v0.8.1, https://github.com/quickfixgo/quickfix/releases/tag/v0.8.1
