### ISSUE TITLE
Can't logon using dynamic session

### ISSUE THREAD

**Issue by yueyingjuesha** [quickfixgo/quickfix#466]
Hi, It seems like after this PR change I can't logon using dynamic session:
https://github.com/quickfixgo/quickfix/pull/446

To me it seem that the code change is only initializing listen ports/listeners on static sessions specified in .cfg configuration file, could you please double check the PR and confirm if I am wrong?

Thanks!

**Comment by mikhailovavexmocom** [comment]
this was originally posted at https://github.com/quickfixgo/quickfix/issues/466

**Comment by mikhailovavexmocom** [comment]
fix approach: https://github.com/quickfixgo/quickfix/pull/522

**Comment by ackleymi** [comment]
Resolved in https://github.com/quickfixgo/quickfix/pull/527
