### ISSUE TITLE
postgres pgx driver not supported with placeholder function

### ISSUE THREAD

**Issue by bvrygud** [quickfixgo/quickfix#487]
Extract of fix config which I am working at

```
PersistMessages=Y
SQLStoreDriver=pgx
SQLStoreDataSourceName=postgres://pgxuser:pgxpass@localhost:5432/testdb
```
Using the above session settings is not able to initiate the session, having the postgres module as https://github.com/jackc/pgx which registers the driver as **pgx**
https://github.com/lib/pq - This module registers the driver as **postgres**. pq repo is not active and they recommend using pgx driver. 

postgresPlaceholder can be used only if the driver is **postgres** and does not support pgx. 
[Code](https://github.com/quickfixgo/quickfix/blob/94d7217c93c22b69951da4d86857852ae89ff94e/sqlstore.go#L89)

```
	if store.sqlDriver == "postgres" {
		store.placeholder = postgresPlaceholder
	}
```

**Comment by Yu-Xie** [comment]
I've encountered the same issue. Looks like it needs to be changed to something like this:
```
if store.sqlDriver == "postgres" || store.sqlDriver == "pgx" {
		store.placeholder = postgresPlaceholder
	}
```
