### ISSUE TITLE
Request to be added as a maintainer

### ISSUE THREAD

**Issue by sylr** [quickfixgo/quickfix#512]
Hi,

My company is building an exchange and is heavily relying on `quickfix-go`. As such we have written a fix client based on quickfixgo (https://github.com/sylr/fix) and also regenerated https://github.com/quickfixgo/fix50sp2/ using the fix50sp2 EP269 which can be found at https://github.com/sylr/quickfixgo-fix50sp2.

I'd like to help this project going forward by assuming a Maintainer role (reviewing, approving and merging PRs).

Regards.

**Comment by totalys** [comment]
Please accept him. This project needs a boost. Don't let it die!
