### ISSUE TITLE
Dynamic Sessions

### ISSUE THREAD

**Issue by shipa988** [quickfixgo/quickfix#521]
Sorry for repeating this issue! it's a real trouble for me! 

> Hi, It seems like after this PR change I can't logon using dynamic session:
> https://github.com/quickfixgo/quickfix/pull/446
> 
> To me it seem that the code change is only initializing listen ports/listeners on static sessions specified in .cfg configuration file, could you please double check the PR and confirm if I am wrong?
> 
> Thanks!

**Comment by mikhailovavexmocom** [comment]
this was originally posted at https://github.com/quickfixgo/quickfix/issues/466

**Comment by ackleymi** [comment]
Resolved in https://github.com/quickfixgo/quickfix/pull/527
