### ISSUE TITLE
Any thoughts on creating a new label so that go get @latest doesn't pull a really old version?

### ISSUE THREAD

**Issue by pilotso11** [quickfixgo/quickfix#535]
Currenty the default install "go get github.org/quickfixgo/quickfix@latest" pulls the v0.0.6 tag, from 2017.
Perhaps adding a fresher tag would be good?  Sure we can pull from @main, but something between 5 years and yesterday might be handy for people?    Is there a way to encourage the community to elect a stable build?

**Comment by ackleymi** [comment]
Thanks for the thoughts, I do have a plan to tag a new version this week, I'll circle back on this ticket when I do

**Comment by ackleymi** [comment]
New version 0.7.0 is available :)
