### ISSUE TITLE
Initiator.Start() stalls in v0.8.0

### ISSUE THREAD

**Issue by paul-leydier** [quickfixgo/quickfix#587]
Hi everyone!

Unless I'm mistaken, there might have been a breaking change in the v0.8.0 of this package [here](https://github.com/quickfixgo/quickfix/commit/84d2532d1d831cc0ae0a0a43edb694bc4cd62fec).

To give some context, `i.handleConnection` does not return before the connection is closed, meaning that, with this new line `i.wg.Wait()`, the call `i.Start()` does not return until the connection is closed.

On my side, I have code which starts the initiator and then continues execution in v0.7.0; but stalls on `i.Start()` with v0.8.0.

Maybe this is intended behavior, but it's breaking on my side. Let me know if this is not intended, I can open a PR.

**Comment by ackleymi** [comment]
Hi @paul-leydier  we'll look into this today and cut a new version shortly if needed

**Comment by ackleymi** [comment]
@paul-leydier removed the wait with v0.8.1 https://github.com/quickfixgo/quickfix/releases/tag/v0.8.1 , let me know if that version gives you any more trouble. Closing this one

**Comment by paul-leydier** [comment]
> @paul-leydier removed the wait with v0.8.1 https://github.com/quickfixgo/quickfix/releases/tag/v0.8.1 , let me know if that version gives you any more trouble. Closing this one

Thanks, looks good now!
