### ISSUE TITLE
Support for connection over SSL

### ISSUE THREAD

**Issue by andradei** [quickfixgo/quickfix#63]
Are there plans to add support for secure connections?

**Comment by cbusbey** [comment]
Yep, this is definitely something we'd like to get in.  In the meantime, you can always use stunnel.

**Comment by botvs** [comment]
change quickfix/connection.go line 26 to 

```
		netConn, err := tls.Dial("tcp", address, &tls.Config{InsecureSkipVerify: true})
```

can support ssl
