### ISSUE TITLE
Initiator got stuck during stopping procedure

### ISSUE THREAD

**Issue by filinvadim** [quickfixgo/quickfix#666]
First of all please excuse me for a lack of information - this is all i have honestly.

I have stopping function wrapper:
```go
func stopInitiator() {
	stopChan := make(chan struct{})
	go func() {
		f.cli.Stop()
		close(stopChan)
	}()
	select {
	case <-stopChan:
	case <-time.After(time.Minute):
		panic("fix initiator stopping timeout")
	}
}
```

Expected behavior: successful initiator stopping.
Given behavior: `initiator.Stop()` method got stuck eternally -> panic.

**Comment by ackleymi** [comment]
Hi, I found a bug with initiator stops hanging, I fixed it here - https://github.com/quickfixgo/quickfix/pull/669. Please let me know if you have further thoughts.

**Comment by filinvadim** [comment]
I believe it's still stuck during reconnect tryouts
