### ISSUE TITLE
Generate custom dictionary

### ISSUE THREAD

**Issue by ericdeshayes** [quickfixgo/quickfix#76]
Is there any plan on creating custom dictionary from a custom dictionary as every (if not all) FIX RoE as customized and not fully compliant with the protocol?

**Comment by cbusbey** [comment]
Hi @ericdeshayes,

Take a look at quickfix/_gen its sub packages.  All of the standard FIX messages included with QuickFIX/Go are generated with these code generation utilities and the FIX data dictionaries used by the other QuickFIX libraries.  If you have a custom FIX data dictionary, you can simply generate your own messages and fields using the code generator.
