### ISSUE TITLE
FIX Log parser

### ISSUE THREAD

**Issue by ericdeshayes** [quickfixgo/quickfix#77]
I am trying to read FIX logs but I am struggling to do it without exposing the ParseMessage function.

There could be a better alternative that I am missing?

**Comment by cbusbey** [comment]
I'm quite clear on what your use case is.  You have a FIX log that you would like to parse with QuickFIX/Go?

**Comment by cbusbey** [comment]
I suspect this is a dup of #110 which has a bit more info.  Closing.
