### ISSUE TITLE
Only one acceptor connection can be created

### ISSUE THREAD

**Issue by pfong** [quickfixgo/quickfix#82]
FIX engine should be able to support multiple acceptor connections, i.e. allow user to define SocketAcceptAddress and SocketAcceptPort at the Session level.

**Comment by cbusbey** [comment]
None of the other QuickFIX versions supports this functionality.  If you need multiple accept sockets, simply have multiple acceptors.

**Comment by chaoyi** [comment]
It seems quickfix since 1.12.0 supports this functionality. https://github.com/quickfix/quickfix/blob/c3e9d06fb95dba4a9d70ec7870b153063e378340/NEWS#L356
